version: '3'

services:
   db:
     image: dbimg
     volumes:
         - /opt/data:/var/lib/mysql
     restart: always
     ports:
       - "3363:3306"
     hostname: db
     environment:
       MYSQL_ROOT_PASSWORD: 1234
       MYSQL_DATABASE: flipkartdb
       MYSQL_USER: root
       
   webapi:
     depends_on:
       - db
     image: webimg 
     hostname: webapi
     ports:
       - "8081:8080"
     restart: always
