version: '3'

services:
   db:
     image: mysql
     command: --max_allowed_packet=100000
     restart: always
     ports:
       - "3363:3306"
     environment:
       MYSQL_ROOT_PASSWORD: 1234
       MYSQL_DATABASE: flipkartdb
     volumes:
       - ./flipkart_data.sql:/docker-entrypoint-initdb.d/flipkart_data.sql
       
   webapi:
     depends_on:
       - db
     image: project 
     ports:
       - "8081:8080"
     restart: always
     volumes:
       - /data/webapi
