version: '3.3'

services:
   db:
     image: mysql
     volumes:
         - /opt/data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 1589
       MYSQL_DATABASE: flipkartdb
       MYSQL_USER: root
       
   webapi:
     depends_on:
       - db
     image: project 
     ports:
       - "8081:8080"
     restart: always
