version: '3'

services:
   db:
     image: mysql
     command: --max_allowed_packet=100000
     volumes:
         - /opt/data:/var/lib/mysql
     restart: always
     hostname: db
     environment:
       MYSQL_ROOT_PASSWORD: 1234
       MYSQL_DATABASE: flipkartdb
       MYSQL_USER: root
       
   webapi:
     depends_on:
       - db
     image: project 
     hostname: webapi
     ports:
       - "8081:8080"
     restart: always
